apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-persistenceagent
spec:
  replicas: {{< .Values.kubeflow_tools.pipelines.kfpPersistenceagent.replicas >}}
  template:
    spec:
      containers:
        - name: ml-pipeline-persistenceagent
          resources:
{{< .Values.kubeflow_tools.pipelines.kfpPersistenceagent.resources | toYAML | indent 12 >}}
          env:
            ## ================================
            ## UserID Configs
            ## ================================
            - name: KUBEFLOW_USERID_HEADER
              value: null
              valueFrom:
                configMapKeyRef:
                  name: pipeline-install-config
                  key: USERID_HEADER
            - name: KUBEFLOW_USERID_PREFIX
              value: null
              valueFrom:
                configMapKeyRef:
                  name: pipeline-install-config
                  key: USERID_PREFIX
