apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorboards-web-app-deployment
  namespace: kubeflow
spec:
  replicas: {{< .Values.kubeflow_tools.tensorboards.tensorboardsWebApp.replicas >}}
  template:
    spec:
      containers:
        - name: tensorboards-web-app
          resources:
{{< .Values.kubeflow_tools.tensorboards.tensorboardsWebApp.resources | toYAML | indent 12 >}}
