apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: {{< .Values.kubeflow_tools.tensorboards.controller.replicas >}}
  template:
    spec:
      containers:
        - name: manager
          resources:
{{< .Values.kubeflow_tools.tensorboards.controller.resources | toYAML | indent 12 >}}
